language: python
python:
  - 2.7
env:
  - USE_POSTGRES=true
  - USE_POSTGRES=

services:
  - postgres

matrix:
  allow_failures:
    - env: USE_POSTGRES=true

install:
 - sudo pip install --upgrade pip
 - sudo pip install coveralls
 - sudo pip install codecov
 - sudo cp /usr/lib/*/libz.so $VIRTUAL_ENV/lib

script: coverage run --source="mysite" manage.py test

before_install:
 - deactivate
 - sudo apt-get update -qq
 - sudo apt-get build-dep -qq python-imaging
 - sudo apt-get install libjpeg-dev python-psycopg2
 - git config --global user.name TravisDummy
 - git config --global user.email dummy@travis-ci.org


before_script:
  - psql -c 'create database openhatch' -U postgres

after_success:
  - coveralls
  - codecov
